name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack shims
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: |
            yarn.lock
            .yarn/install-state.gz
      - name: Activate workspace Yarn
        run: |
          corepack enable
          corepack prepare "$(node -p "require('./package.json').packageManager")" --activate
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build packages
        run: yarn build
      - name: Run tests
        run: yarn test
