name: Release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: write
  issues: read
  pull-requests: write
  id-token: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack shims
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: |
            yarn.lock
            .yarn/install-state.gz
      - name: Activate workspace Yarn
        run: |
          corepack enable
          corepack prepare "$(node -p "require('./package.json').packageManager")" --activate
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
      - name: Build package
        run: yarn build

  release:
    needs: quality
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack shims
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: |
            yarn.lock
            .yarn/install-state.gz
      - name: Activate workspace Yarn
        run: |
          corepack enable
          corepack prepare "$(node -p "require('./package.json').packageManager")" --activate
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build package
        run: yarn build

      - name: Publish with Changesets
        uses: changesets/action@v1
        with:
          version: yarn version-packages
          publish: yarn release
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: 'true'

      - name: Upload npm debug logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: npm-debug-logs
          path: /home/runner/work/touchspin-vue/touchspin-vue/.npm-cache/_logs/*.log
